### ISSUE TITLE
concerning pseudo labels

### ISSUE THREAD

**Issue by Daniellli** [duxiaodan/intrinsic-lora#2]
Hi,
Thank you for your contribution.
I am preparing to reproduce the results reported in your paper. To facilitate a more efficient replication process, could you kindly share the pseudo labels you generated? Thank you for your assistance.

**Comment by duxiaodan** [comment]
Hi Daniellli, I just used the inference code from [omnidata](https://github.com/EPFL-VILAB/omnidata/blob/main/omnidata_tools/torch/demo.py) and [zoedepth](https://github.com/isl-org/ZoeDepth/blob/main/README.md?plain=1#L87) without any significant changes. I'm travelling so I can't do any serious work right now. However don't hesitate to let me know if you encounter any problems using their code

**Comment by Daniellli** [comment]
Thank you for your prompt response.

I have generated the pseudo labels and am ready to begin training with them.  I am curious about the training time and hardware settings. Could you provide the supplementary materials when you are available so that I can review them myself?

Moreover, would you mind providing the checkpoint of the model you trained when you are available?

Thank you once again.

**Comment by duxiaodan** [comment]
When trained on a single RTX6000 gpu, single-step model usually converges after 5 hrs. AugUNet can take over 12 hours to converge. I usually train single-step model for 8 hrs and AugUNet for 24 hrs. I can provide more details when I come back.

Just out of curiosity: which model are you going to work with? The single-step one or the multi-step one?

**Comment by Daniellli** [comment]
I am planning to use the single-step model as it seems to have higher quantitative results. By the way, could you provide the evaluation code when you are available?
Thank you for your attention.

**Comment by duxiaodan** [comment]
Gotcha. Thank you for using our code and your interest in our paper! I used this [code](https://github.com/EPFL-VILAB/omnidata/blob/main/paper_code/evaluation_metrics.py) for evaluation.

**Comment by duxiaodan** [comment]
Hi, happy new year!

Just included the link to ckpts of normal and depth in README. Feel free to reach out at xdu@ttic.edu if you have further questions

**Comment by Daniellli** [comment]
Hi, happy new year! 
Could you please provide the checkpoint files for albedo and shading?

**Comment by duxiaodan** [comment]
Glad you are also interested in albedo and shading! Just added those ckpts as well.

**Comment by duxiaodan** [comment]
Clossing this issue now. Feel free to reopen if you have further questions

**Comment by danushkv** [comment]
Hi @duxiaodan !!
Thanks for this wonderful work. I'm interested in generating pseudo albedo and shading maps. I saw the reference to Paradigms to generate them. However, I couldn't find code online. Could you kindly share the code to generate these maps ?
