### ISSUE TITLE
Inference code for pretrained checkpoints

### ISSUE THREAD

**Issue by k8xu** [duxiaodan/intrinsic-lora#3]
Hello,

Could you please provide a Python script to use the pretrained LoRA checkpoints for a folder of images?

Thank you!

**Comment by duxiaodan** [comment]
Hello,

Thank you for your interest in our work. Please find inference code at https://github.com/duxiaodan/intrinsic-lora/blob/main/inference_sd_single.py

**Comment by k8xu** [comment]
Thank you for your quick response!
