### ISSUE TITLE
Question:  could a textual inversion be made to get these models to express these concepts?

### ISSUE THREAD

**Issue by Lerc** [duxiaodan/intrinsic-lora#5]
If a text to image generator internally has a particular concept,  would it follow that all they need to generate an output showing that concept is an appropriate input requesting it?    For instance could you use textual inversion to make an input embedding to communicate "output only what you perceive to be albedo"

**Comment by duxiaodan** [comment]
Hi Lerc,

Thank you for your comment. Exactly, in an ideal world, indeed "an appropriate input" should be all you need to let them generate a concept. If you consider a specific intrinsic as a special "style", then techniques that work for stylization should also work for intrinsics extraction. However, practically, we've tried many methods, including textual inversion, but none of them really worked as well as LoRA. LoRA helps the model to convert what they know about an intrinsics, say surface normal, to our definition of surface normal.
