### ISSUE TITLE
ComfyUI implementation and sourcing the pretrained LoRAs

### ISSUE THREAD

**Issue by kijai** [duxiaodan/intrinsic-lora#6]
Hey!

I made a custom node for ComfyUI to allow the one step sampling for the LoRAs, it works great and shows lots of potential already!
I wanted to ask if you would be okay with me uploading the LoRAs to some easier to access location than gdrive, or even bundling with the custom node code, or if you would be willing to do that yourself? For example hugging face.

Thank you for the great work regardless!

**Comment by duxiaodan** [comment]
Hi kijai,

Thank you for experimenting with our work! Please feel free to upload the LoRAs to other locations. I'll be grateful if you could share a link to your node once you finish the integration.

**Comment by kijai** [comment]
> Hi kijai,
> 
> Thank you for experimenting with our work! Please feel free to upload the LoRAs to other locations. I'll be grateful if you could share a link to your node once you finish the integration.

Alright, thank you!
I have added the node to my generic node pack as it doesn't require any additional dependencies, integrates easily into ComfyUI:
![image](https://github.com/duxiaodan/intrinsic-lora/assets/40791699/51d6a003-dec7-4d99-a900-9741915f149b)

https://github.com/kijai/ComfyUI-KJNodes

**Comment by duxiaodan** [comment]
That looks awesome. Thank you for your effort!

**Comment by duxiaodan** [comment]
Hi kijai,

Do you mind if I include the link to your KJNodes github repo in my main readme file?

**Comment by kijai** [comment]
> Hi kijai,
> 
> Do you mind if I include the link to your KJNodes github repo in my main readme file?

I don't mind at all!

**Comment by ivied7** [comment]
So excellent,both you are！
