### ISSUE TITLE
Blender addon

### ISSUE THREAD

**Issue by neph1** [duxiaodan/intrinsic-lora#7]
Hey. Thank you for your work. I was interested in trying it out in a workflow, so I created a Blender addon.

https://github.com/neph1/blender-intrinsic-lora

Example video:
https://youtu.be/oTtM4-GYlXk

I also uploaded your loras in safetensors format to huggingface. Hope that is OK.

https://huggingface.co/neph1/intrinsic_lora

**Comment by duxiaodan** [comment]
Wow nice work neph1. Thank you very much! Do you mind if I add a link to your blender addon in my main readme file?
